---
# tasks file for nexus-install
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Ansible check file exists example.
  stat:
    path: /opt/nexus/
  register: folder_nexus

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
  when: ansible_os_family == "RedHat"
  become: yes

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ package_required }}"
  become: yes

- name: Include install nexus
  include: install.yml
  when: nexus is defined

- name: Include configure nexus
  include: configure.yml
  when: nexus is defined
